services:
    dj4h:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dj4h
        env_file:
            - .env
        volumes:
            - ./data:/app/data