---
services:
  dj4h-bot:
    image: ghcr.io/asynccommunitydiscord/dj4h:latest
    container_name: dj4h-bot
    restart: unless-stopped
    environment:
      BOT_TOKEN: $BOT_TOKEN
      # DEBUG_GUILD_ID:
      DATABASE_PATH: /app/data/dj4h.db
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
