name: Publish DJ4H Docker image

on:
    push:
        branches: [ 'master' ]

env:
    REGISTRY: ghcr.io
    OWNER: gravendev
    NAME: dj4h

jobs:
    push_to_registry:
        name: Push Docker image to Github Package
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

        permissions:
            contents: read
            packages: write

        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4

            -   name: Log in to GHCR.io
                uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
                with:
                    context: ./
                    file: ./Dockerfile
                    push: true
                    tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.NAME }}